// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: anomalies.sql

package database

import (
	"context"
	"database/sql"
)

const getCityAnomaly = `-- name: GetCityAnomaly :one
SELECT city, date, pm25, is_anomaly, severity FROM anomalies WHERE city=$1
`

type GetCityAnomalyRow struct {
	City      sql.NullString
	Date      sql.NullTime
	Pm25      sql.NullFloat64
	IsAnomaly sql.NullBool
	Severity  sql.NullString
}

func (q *Queries) GetCityAnomaly(ctx context.Context, city sql.NullString) (GetCityAnomalyRow, error) {
	row := q.db.QueryRowContext(ctx, getCityAnomaly, city)
	var i GetCityAnomalyRow
	err := row.Scan(
		&i.City,
		&i.Date,
		&i.Pm25,
		&i.IsAnomaly,
		&i.Severity,
	)
	return i, err
}
