// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: city_pollution.sql

package database

import (
	"context"
	"database/sql"
)

const getCityPollutionRecord = `-- name: GetCityPollutionRecord :many
SELECT city, date, pm25, pm10, no2, co FROM city_pollution WHERE city=$1
`

type GetCityPollutionRecordRow struct {
	City sql.NullString
	Date sql.NullTime
	Pm25 sql.NullFloat64
	Pm10 sql.NullFloat64
	No2  sql.NullFloat64
	Co   sql.NullFloat64
}

func (q *Queries) GetCityPollutionRecord(ctx context.Context, city sql.NullString) ([]GetCityPollutionRecordRow, error) {
	rows, err := q.db.QueryContext(ctx, getCityPollutionRecord, city)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCityPollutionRecordRow
	for rows.Next() {
		var i GetCityPollutionRecordRow
		if err := rows.Scan(
			&i.City,
			&i.Date,
			&i.Pm25,
			&i.Pm10,
			&i.No2,
			&i.Co,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
