// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Anomaly struct {
	ID                  int32
	City                sql.NullString
	Date                sql.NullTime
	Pm25                sql.NullFloat64
	ReconstructionError sql.NullFloat64
	Threshold           sql.NullFloat64
	IsAnomaly           sql.NullBool
	Severity            sql.NullString
	CreatedAt           sql.NullTime
}

type CityPollution struct {
	ID        int32
	City      sql.NullString
	Date      sql.NullTime
	Pm25      sql.NullFloat64
	Pm10      sql.NullFloat64
	No        sql.NullFloat64
	No2       sql.NullFloat64
	Nox       sql.NullFloat64
	Nh3       sql.NullFloat64
	So2       sql.NullFloat64
	Co        sql.NullFloat64
	Ozone     sql.NullFloat64
	Benzene   sql.NullFloat64
	Month     sql.NullInt32
	Season    sql.NullString
	DayOfWeek sql.NullInt32
	Year      sql.NullInt32
}

type LstmPrediction struct {
	ID            int32
	City          sql.NullString
	Date          sql.NullTime
	PredictedPm25 sql.NullFloat64
	ActualPm25    sql.NullFloat64
	Rmse          sql.NullFloat64
	Mae           sql.NullFloat64
	R2Score       sql.NullFloat64
	CreatedAt     sql.NullTime
}

type ModelMetric struct {
	ID         int32
	City       sql.NullString
	ModelType  sql.NullString
	Rmse       sql.NullFloat64
	Mae        sql.NullFloat64
	R2Score    sql.NullFloat64
	Confidence sql.NullFloat64
	TrainedAt  sql.NullTime
}

type SourceAnalysis struct {
	ID             int32
	City           sql.NullString
	TopSource1     sql.NullString
	TopSource2     sql.NullString
	TopSource3     sql.NullString
	Pm10Importance sql.NullFloat64
	CoImportance   sql.NullFloat64
	Nh3Importance  sql.NullFloat64
	Confidence     sql.NullFloat64
	CreatedAt      sql.NullTime
}
