// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: model_metrics.sql

package database

import (
	"context"
	"database/sql"
)

const getModelMetrics = `-- name: GetModelMetrics :many
SELECT city, model_type, rmse, mae, r2_score, confidence FROM model_metrics
`

type GetModelMetricsRow struct {
	City       sql.NullString
	ModelType  sql.NullString
	Rmse       sql.NullFloat64
	Mae        sql.NullFloat64
	R2Score    sql.NullFloat64
	Confidence sql.NullFloat64
}

func (q *Queries) GetModelMetrics(ctx context.Context) ([]GetModelMetricsRow, error) {
	rows, err := q.db.QueryContext(ctx, getModelMetrics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetModelMetricsRow
	for rows.Next() {
		var i GetModelMetricsRow
		if err := rows.Scan(
			&i.City,
			&i.ModelType,
			&i.Rmse,
			&i.Mae,
			&i.R2Score,
			&i.Confidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
