// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: source_analysis.sql

package database

import (
	"context"
	"database/sql"
)

const getSourceAnalysis = `-- name: GetSourceAnalysis :one
SELECT city, top_source_1, top_source_2, pm10_importance, confidence FROM source_analysis WHERE city=$1
`

type GetSourceAnalysisRow struct {
	City           sql.NullString
	TopSource1     sql.NullString
	TopSource2     sql.NullString
	Pm10Importance sql.NullFloat64
	Confidence     sql.NullFloat64
}

func (q *Queries) GetSourceAnalysis(ctx context.Context, city sql.NullString) (GetSourceAnalysisRow, error) {
	row := q.db.QueryRowContext(ctx, getSourceAnalysis, city)
	var i GetSourceAnalysisRow
	err := row.Scan(
		&i.City,
		&i.TopSource1,
		&i.TopSource2,
		&i.Pm10Importance,
		&i.Confidence,
	)
	return i, err
}
